# status bar
set -g status on
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 50
set -g status-style "bg=default,fg=colour223"

set -g status-left  '#[bold][ #S ]'
set -g status-right '#[bold][ %d/%m %H:%M ] #{prefix_highlight}'

# windows
setw -g window-status-format          ' #I#[fg=colour244]:#[fg=colour244]#W#[fg=colour244] '
setw -g window-status-current-format  ' #I#[bold,fg=colour231] #W#[fg=colour231]#F '

# pane borders
set -g pane-border-style        "fg=colour240"
set -g pane-active-border-style "fg=colour39"   # cyan accent

# copy/command messages + copy-mode
set -g message-style "bg=colour237,fg=colour223"
set -g mode-style    "bg=colour237,fg=colour231"

# prefix-timeout overlays
set -g display-panes-active-colour "colour39"
set -g display-panes-colour        "colour240"

# clock
set -g clock-mode-colour "colour39"
