# status bar
set -g status on
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 50
set -g status-style "bg=default,fg=colour238"

set -g status-left  '#[bold][ #S ]'
set -g status-right '#[bold][ %d/%m %H:%M ] #{prefix_highlight}'

# windows
setw -g window-status-format          ' #I#[fg=colour241]:#[fg=colour241]#W#[fg=colour241] '
setw -g window-status-current-format  ' #I#[bold,fg=colour0] #W#[fg=colour0]#F '

# pane borders
set -g pane-border-style        "fg=colour250"
set -g pane-active-border-style "fg=colour31"   # blue accent

# copy/command messages + copy-mode
set -g message-style "bg=colour254,fg=colour238"
set -g mode-style    "bg=colour254,fg=colour0"

# prefix-timeout overlays
set -g display-panes-active-colour "colour31"
set -g display-panes-colour        "colour248"

# clock
set -g clock-mode-colour "colour31"
